# Generated by Django 3.2.12 on 2022-03-30 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20220330_0022'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureList',
            fields=[
                ('feature_list_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='FeatureListToFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_count', models.IntegerField(max_length=25)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.feature')),
                ('feature_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.featurelist')),
            ],
        ),
    ]
