# Generated by Django 3.2.12 on 2022-03-30 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_featurelist_featurelisttofeature'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideLine',
            fields=[
                ('guideline_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('content', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('room_address', models.CharField(max_length=255)),
                ('other_detail', models.CharField(max_length=255)),
                ('qe_code_url', models.CharField(max_length=255)),
                ('feature_list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.featurelist')),
                ('guideline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.guideline')),
            ],
        ),
    ]
