# Generated by Django 3.2.12 on 2022-04-06 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_guideline_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('start_time', models.CharField(max_length=25)),
                ('end_time', models.CharField(max_length=25)),
                ('create_time', models.CharField(max_length=25)),
                ('confirm', models.BooleanField(default=False)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.room')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.student')),
            ],
        ),
    ]
