# Generated by Django 3.2.12 on 2022-05-25 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_auto_20220413_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurelisttofeature',
            name='feature_count',
            field=models.IntegerField(),
        ),
    ]
