# Generated by Django 3.2.12 on 2022-05-25 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_booking_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='picture',
        ),
        migrations.AddField(
            model_name='room',
            name='picture',
            field=models.CharField(default='', max_length=50),
        ),
    ]
